#!/system/bin/sh
# Copyright (c) 2012, Jake "redmaner" van der Putten
# Engengis project

READSPEED=/system/etc/init.d/S35sdreadspeed
SETTINGS=/data/settings.conf

mount -o remount,rw /system
clear
echo
echo " #########################"
echo " #  Engengis.Charlie     #" 
echo " #########################"
echo 
echo " 1 - Set SD-Readspeed to 256kb"
echo " 2 - Set SD-Readspeed to 512kb"
echo " 3 - Set SD-Readspeed to 1024kb"
echo " 4 - Set SD-Readspeed to 2048kb"
echo " 5 - Set SD-Readspeed to 3072kb"
echo " 6 - Set SD-Readspeed to 4096kb"
echo " 7 - Remove SD-Readspeed settings"
echo " b - Back"
if [ -e $READSPEED ]; then
if [ $(cat $READSPEED | grep "# SD-Readspeed 256" | wc -l) -gt 0 ]; then
      echo
      echo "--------------------------------"
      echo "SD-Readspeed = 256kb"
elif [ $(cat $READSPEED | grep "# SD-Readspeed 512" | wc -l) -gt 0 ]; then
      echo
      echo "--------------------------------"
      echo "SD-Readspeed = 512kb"
elif [ $(cat $READSPEED | grep "# SD-Readspeed 1024" | wc -l) -gt 0 ]; then
      echo
      echo "--------------------------------"
      echo "SD-Readspeed = 1024kb"
elif [ $(cat $READSPEED | grep "# SD-Readspeed 2048" | wc -l) -gt 0 ]; then
      echo
      echo "--------------------------------"
      echo "SD-Readspeed = 2048kb"
elif [ $(cat $READSPEED | grep "# SD-Readspeed 3072" | wc -l) -gt 0 ]; then
      echo
      echo "--------------------------------"
      echo "SD-Readspeed = 3072kb"
elif [ $(cat $READSPEED | grep "# SD-Readspeed 4096" | wc -l) -gt 0 ]; then
      echo
      echo "--------------------------------"
      echo "SD-Readspeed = 4096kb"
fi;
fi;
echo
echo -n "Please enter your choice:"; read option;
  case "$option" in
    "1")
    if [ -e $READSPEED ]; then
          rm -f $READSPEED
    fi;
    cp /system/etc/engengis/S35sd256 $READSPEED;
    chmod 777 $READSPEED;
    sed -i '/sdreadspeed=*/ d' $SETTINGS;
    echo "sdreadspeed=256" >> $SETTINGS;
    clear
    engengisr
    ;;
    "2")
    if [ -e $READSPEED ]; then
          rm -f $READSPEED
    fi;
    cp /system/etc/engengis/S35sd512 $READSPEED;
    chmod 777 $READSPEED;
    sed -i '/sdreadspeed=*/ d' $SETTINGS;
    echo "sdreadspeed=512" >> $SETTINGS;
    clear
    engengisr
    ;;
    "3")
    if [ -e $READSPEED ]; then
          rm -f $READSPEED
    fi;
    cp /system/etc/engengis/S35sd1024 $READSPEED;
    chmod 777 $READSPEED;
    sed -i '/sdreadspeed=*/ d' $SETTINGS;
    echo "sdreadspeed=1024" >> $SETTINGS;
    clear
    engengisr
    ;;
    "4")
    if [ -e $READSPEED ]; then
          rm -f $READSPEED
    fi;
    cp /system/etc/engengis/S35sd2048 $READSPEED;
    chmod 777 $READSPEED;
    sed -i '/sdreadspeed=*/ d' $SETTINGS;
    echo "sdreadspeed=2048" >> $SETTINGS;
    clear
    engengisr
    ;;
    "5")
    if [ -e $READSPEED ]; then
          rm -f $READSPEED
    fi;
    cp /system/etc/engengis/S35sd3072 $READSPEED;
    chmod 777 $READSPEED;
    sed -i '/sdreadspeed=*/ d' $SETTINGS;
    echo "sdreadspeed=3072" >> $SETTINGS;
    clear
    engengisr
    ;;
    "6")
    if [ -e $READSPEED ]; then
          rm -f $READSPEED
    fi;
    cp /system/etc/engengis/S35sd4096 $READSPEED;
    chmod 777 $READSPEED;
    sed -i '/sdreadspeed=*/ d' $SETTINGS;
    echo "sdreadspeed=4096" >> $SETTINGS;
    clear
    engengisr
    ;;
    "7")
    if [ -e $READSPEED ]; then
          rm -f $READSPEED
    fi;
    echo
    echo
    echo "Removed SD-Readspeed settings"
    sed -i '/sdreadspeed=*/ d' $SETTINGS;
    echo "sdreadspeed=default" >> $SETTINGS;
    sleep 2
    clear
    engengisr
    ;;
    "b" | "B")
    clear
    engengis
    ;;
  esac



