#!/system/bin/sh
# Copyright (c) 2012, redmaner

# Performance governor
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]; then
        echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi


