#!/system/bin/sh
# Copyright (c) 2012, redmaner

# Interactive governor
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]; then
        echo "interactive" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi


