#!/system/bin/sh
# Copyright (c) 2012, redmaner

# Ondemand governor
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]; then
        echo "ondemand" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi


