#!/system/bin/sh
# Copyright (c) 2012, redmaner

# Conservative governor
if [ -e /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ]; then
        echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
fi


